# Generated by Django 3.0.4 on 2020-03-10 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Name of this project', max_length=128)),
                ('Description', models.TextField(help_text='Description for this project')),
            ],
        ),
        migrations.AddField(
            model_name='partcountmodel',
            name='Bin',
            field=models.CharField(blank=True, help_text='Bin ID this part is stored in', max_length=32),
        ),
        migrations.AddField(
            model_name='partmodel',
            name='MfgName',
            field=models.CharField(blank=True, help_text='Name of the part manufactor', max_length=128),
        ),
        migrations.AlterField(
            model_name='partmodel',
            name='Value',
            field=models.FloatField(blank=True, help_text='Value for this part', null=True),
        ),
        migrations.CreateModel(
            name='ProjectPartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(help_text='Quantity of parts required')),
                ('Part', models.ForeignKey(help_text='Part required', on_delete=django.db.models.deletion.CASCADE, to='app.PartModel')),
                ('Project', models.ForeignKey(help_text='Project this part is required for', on_delete=django.db.models.deletion.CASCADE, to='app.ProjectModel')),
            ],
        ),
    ]
