# Generated by Django 3.0.4 on 2020-03-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partmodel',
            name='UnitID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partmodel',
            name='Attributes',
            field=models.ManyToManyField(blank=True, help_text='Part this attribute is assigned to', to='app.PartAttrModel'),
        ),
        migrations.AlterField(
            model_name='partmodel',
            name='DataSheet',
            field=models.FileField(blank=True, help_text='Datasheet for this part', null=True, upload_to='data_sheets/%m/'),
        ),
        migrations.AlterUniqueTogether(
            name='partmodel',
            unique_together={('Name', 'Value'), ('Value', 'UnitID')},
        ),
        migrations.RemoveField(
            model_name='partmodel',
            name='Unit',
        ),
        migrations.DeleteModel(
            name='MeasurementUnitModel',
        ),
    ]
