# Generated by Django 3.0.4 on 2020-03-13 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partmodel',
            name='Package',
            field=models.ForeignKey(blank=True, help_text='Package of this part', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PackageModel'),
        ),
        migrations.AlterUniqueTogether(
            name='partmodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='partmodel',
            name='UnitID',
        ),
    ]
