# Generated by Django 3.0.4 on 2020-03-10 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200309_1808'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partmodel',
            unique_together={('Value', 'UnitID')},
        ),
    ]
